In [3]:
## https://mofanpy.com/

## Numpy 合并
## vertical stack  vertical => 垂直
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


In [4]:
## horizontal stack horizontal => 水平的
d = np.hstack((a,b))
print(d)

[1 2 3 4 5 6]


In [3]:
## concatenate   多个array合并  concatenate => 连接
import numpy as np
aa = np.arange(24).reshape(4,6)
bb = np.arange(24,48).reshape(4,6)
e = np.concatenate((aa,bb), axis=0)
f = np.concatenate((aa,bb), axis=1)
print(aa)
print(bb)
print(e)
print(f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
[[ 0  1  2  3  4  5 24 25 26 27 28 29]
 [ 6  7  8  9 10 11 30 31 32 33 34 35]
 [12 13 14 15 16 17 36 37 38 39 40 41]
 [18 19 20 21 22 23 42 43 44 45 46 47]]


In [14]:
##  numpy array 分割  np.split(), 分割完之后是一个list,里面每一个元素都是一个array
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)
print(np.split(A,3,axis=0))
print(type(A))
print(type(np.split(A,3,axis=0)))

## 另一种分割方法 np.vsplit()  np.hsplit()
print('Another method -------------- ####')
print(np.vsplit(A,3))
print(np.hsplit(A,2))

## 不等量分割  np.array_split()
print('\n')
print(np.array_split(A, 3, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
<class 'numpy.ndarray'>
<class 'list'>
Another method -------------- ####
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [16]:
### numpy copy  深拷贝浅拷贝概念  对比list
import numpy,copy
aa = np.array([1,2,3])
bb = aa
aa[0] = 99
print(bb)

bb = aa[:]  ## 这种形式改变aa的值，bb的值也会随之改变
print(aa)
aa[1] = 99
print(bb)

cc = np.copy(aa)
aa[2] = 99
print(aa)
print(cc)

print('list ')

[99  2  3]
[99  2  3]
[99 99  3]
[99 99 99]
[99 99  3]


In [23]:
### list copy
import copy
aa = [1,2,3,[4,5,6]]
bb = aa[:]
aa[0] = 99  ##改变aa列表最外层元素，bb的值是不变的
print('aa', aa)
print('bb', bb)
aa[3][0] = 99  ##改变aa列表可变类型元素时，bb的值跟着改变的
print('aa', aa)
print('bb', bb)
## 第三种方式
print('Demo copy method')
aa = [1,2,3,[4,5,6]]
bb = copy.copy(aa)  ##相当于bb=aa[:]
aa[3][0] = 99
aa[0] = 99
print('aa', aa)
print('bb', bb)
## 深拷贝
print('Demo deep copy method')
aa = [1,2,3,[4,5,6]]
bb = copy.deepcopy(aa)
aa[3][0] = 99
aa[0] = 99
print('aa', aa)
print('bb', bb)

aa [99, 2, 3, [4, 5, 6]]
bb [1, 2, 3, [4, 5, 6]]
aa [99, 2, 3, [99, 5, 6]]
bb [1, 2, 3, [99, 5, 6]]
Demo copy method
aa [99, 2, 3, [99, 5, 6]]
bb [1, 2, 3, [99, 5, 6]]
Demo deep copy method
aa [99, 2, 3, [99, 5, 6]]
bb [1, 2, 3, [4, 5, 6]]
